name: run-monitor

on:
  schedule:
    - cron: '30 5 * * *' # 11:00 AM IST
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run-monitor:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run monitor
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          OBJECT_KEY: uit_alwar_plots.json
          OBJECT_KEY_NEWS: uit_alwar_news.json
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_MIN_INTERVAL_MS: '1200'
          TELEGRAM_MAX_MESSAGES: '20'
        run: python lambda_function.py
